### ISSUE TITLE
deprecated componentWillMount & componentWillReceiveProps

### ISSUE THREAD

**Issue by TFLXX** [tjrexer/react-notifications#11]
I'm getting the following warnings in console.
![image](https://user-images.githubusercontent.com/6446164/77200743-7e79ed00-6aeb-11ea-93a9-1e48303629c9.png)

Take a look at the [gradual-migration-path](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path)

**Comment by risentveber** [comment]
Updated in https://github.com/tjrexer/react-notifications/commit/fa4f4c71a2678c085d2a663ab092bb3dbe00c30e

**Comment by TFLXX** [comment]
Okay, maybe I am using an older version, but I cannot see any changes to `componentWillReceiveProps`.

I would fix it by myself, but actually im pretty out of time for now.

**Comment by risentveber** [comment]
@ThaFlaxx see beta https://github.com/tjrexer/react-notifications/releases/tag/v1.6.0-beta.1

**Comment by TFLXX** [comment]
Alright, my bad then. Thanks :)
