### ISSUE TITLE
Can't resolve './fonts/notification.eot'

### ISSUE THREAD

**Issue by benlieb** [tjrexer/react-notifications#16]
Getting error: Module not found: Error: Can't resolve './fonts/notification.eot'

![image](https://user-images.githubusercontent.com/634562/80289093-3f921500-86f1-11ea-966e-468bc855bc07.png)

All my css is loaded this way (above). I tried doing this in my component (which I'd rather not do):

``` javascript
import 'react-notifications/lib/notifications.css'
```

But this only worked in development (not production). Using Rails 6 with webpacker.

**Comment by benlieb** [comment]
Would love to hear a solution to this...

**Comment by benlieb** [comment]
For anyone looking for a solution that works out of the box, I've decided to go with `react-notify-toast`. 


https://www.npmjs.com/package/react-notify-toast

**Comment by tjrexer** [comment]
Issue with `./fonts/notification.eot` is due to how your fonts are loaded for your app.  Check out [issue 46](https://github.com/minhtranite/react-notifications/issues/46) in the original repo for resolutions.
