### ISSUE TITLE
Notifications icon is not working on mobile safari

### ISSUE THREAD

**Issue by Sh031224** [tjrexer/react-notifications#22]
On mobile safari, the icon is not working.

![image](https://user-images.githubusercontent.com/51149996/90335264-acb61700-e00e-11ea-9c44-9325439a8531.jpeg)

Instead of an icon, a rectangle appears.

**Comment by tjrexer** [comment]
Usually the icons failing is due to problems with importing & loading the icons correctly.  See [issue 46](https://github.com/minhtranite/react-notifications/issues/46) in the original repo and let me know if that helps.

**Comment by Sh031224** [comment]
I don't know why the error disapear suddenly today.

**Comment by tjrexer** [comment]
👍
