### ISSUE TITLE
Does it make sense to add a syncing notification?

### ISSUE THREAD

**Issue by jaymu53** [tjrexer/react-notifications#23]
I'm using the library to indicate success and error based on ajax requests initiated by the user. I want to have a syncing notification when its in the middle of an ajax call that either turns into a success or error based on the result.

**Comment by jaymu53** [comment]
I'm using the library to indicate success and error based on ajax requests initiated by the user. I want to have a syncing notification when its in the middle of an ajax call that either turns into a success or error based on the result.

**Comment by tjrexer** [comment]
That's a great use case, I think it is currently achievable with how the notifications are setup.  You can publish one notification, with an extensive timeout, thinking 10 minutes.  When ajax call is complete, you then request the original to be hidden, and call the new success or failure notification.

From a UX perspective, you don't want to just change the existing notification to something else.  The act of notifications in & out will get the users attention and make them aware that something has updated.

Might not need any changes, but would probably be a good example to include as another time of use.  If you want, you can open a PR with the changes your recommending.
