### ISSUE TITLE
NotificationContainer has a method called componentDidUnmount()

### ISSUE THREAD

**Issue by D063520** [tjrexer/react-notifications#27]
Hello,

thank you for the nice library! If I'm not wrong, when I include it I get the following error message in the console:

"NotificationContainer has a method called componentDidUnmount(). But there is no such lifecycle method. Did you mean componentWillUnmount()?"

As far as I see replacing:

componentDidUnmount with componentWillUnmount

will do the job ....

Could you check?

Salut
D063520

**Comment by adamshapiro0** [comment]
I'm seeing the same issue using v1.7.0 with react v16.13.1. It looks like this change happened in commit `2224972` in the recent v1.7.0 update. What was the reason for this change? As far as I'm aware, `componentDidUnmount()` was a suggested feature years ago but was never implemented and the ticket for it was recently closed as a won't fix: https://github.com/facebook/react/issues/6424. Did you mean to rename `componentWillMount()` to `componentDidMount()` instead? Both `componentWillMount()` and `componentWillReceiveProps()` are deprecated and generate console warnings.

**Comment by haw0k** [comment]
Since 1.7.0 react-notifications not working with react 16.13.1 and throw error warning to browser console about componentDidUnmount.
1.6.0 works with console warnings.

**Comment by adamshapiro0** [comment]
Yep, that's what I'm using currently and just ignoring the console warnings about the deprecated functions.

**Comment by mal-clarke-fg** [comment]
Any change of fixing this. Any error messages fails my build pipe. Otherwise I'm going to have to drop your component and find another. 
Thanks

**Comment by tjrexer** [comment]
Sorry, yea.  I over did the lifecycle replacement.  Pushing a fix now, I'll make sure to deprecate any versions that have the bad commit in them.

**Comment by tjrexer** [comment]
Fix has been pushed in v1.7.2 with both v1.7.0 & v1.7.1 being deprecated.  Closing this issue, but please re-open if the problem persists.

If anyone has tests that would help it would be greatly appreciated to avoid shit like this.  I would love to start including some testing, but I'm primarily a back end developer, so I need help with testing suites for snapshots.
