### ISSUE TITLE
Leaving transition is not working.

### ISSUE THREAD

**Issue by thenglong** [tjrexer/react-notifications#32]
entering transition is working, but leaving is not working as the examples provided

**Comment by inzKornel** [comment]
Leaving transition class name is wrong. 
Created PR: [PR](https://github.com/tjrexer/react-notifications/pull/43)

**Comment by marcosdipaolo** [comment]
Any news on this?

**Comment by tjrexer** [comment]
Thanks for the report, sorry for the delay. Been a busy year plus with Covid & a couple personal things. Getting back to issues & PRs here now.
